# Generated by Django 2.0.6 on 2018-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(max_length=200)),
                ('UVI', models.CharField(max_length=200)),
                ('PublishAgency', models.CharField(max_length=200)),
                ('WGS84Lon', models.CharField(max_length=200)),
                ('County', models.CharField(max_length=200)),
                ('WGS84Lat', models.CharField(max_length=200)),
                ('PublishTime', models.CharField(max_length=200)),
            ],
        ),
    ]
